language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

services:
  - docker

env:
  global:
    - secure: pTuC5XVCyo85IzE2pCulnvmsrUA6UicQH+lo2t7x7h+cJQP4YThEI8CE64L1cbH8aBby2+7mZfKvXJTEsLN4FOclY0WzIu8kncRtXmnSysM8cwXSx6ly9Ro3E1JWjT9W7BrWoE6tOMMmv5f0FKTw6b4Rwlv9sFICEERdCIcI6mrRORWwcznoMs2Pg8d0BkZsOm7gcJ7QRL+lfw72fqb8+jCaatzO9WjeUPq5txueVntgaBG+R4Pt6WNHdFPIvYjN7onos9Mw+xeZqZmubG/htTne1ZPQTX7KeI68Hic4rxGEC5eGvXOZoUxfmpoJyoBYb3uPPxWkvsSmgqEMEbTFwtXvLqOkaLXrypGZfksP+yMuBF337uwz8/7eFanYjSsY8qRHDCbQ7xQOboTZyp+soKqQStr6dfLcwsF8v5nRnLBvTBzbgSgCK81SeStH4VcumJoVvWEKPTNx4yRvSK+7W9JuHajR6EXA1YZs0jyfOXM8oDRWaP45CRbu6cKtF+YZykOXYUV8/ZCcFjixmd04VO8M31vnuHN5nF+45JtWkhW2wL62y+x3czc8mMKemhGoCPdR2V+iE38aQ8uHPzyp0dtoXsEBiaypV/c8CvYryirKqGnvNIhmOwgg7k04L5yULkRJlEw27SRnTTyNJ3Dv9NJ+9A7bX4utZcOiSxkohdM=
    - WP_DEVELOP_DIR: ./wordpress
    - PHP_FPM_UID: 2000
    - PHP_FPM_GID: 2000

before_install:
  - nvm install 12

install:
  - composer install
  - npm ci
  - |
    # Download and unpack WordPress.
    curl -sL https://wordpress.org/nightly-builds/wordpress-latest.zip -o /tmp/wordpress-latest.zip
    unzip -q /tmp/wordpress-latest.zip -d /tmp
    mkdir -p wordpress/src
    mv /tmp/wordpress/* wordpress/src
    # Create the upload directory with permissions that Travis can handle.
    mkdir -p wordpress/src/wp-content/uploads
    chmod 767 wordpress/src/wp-content/uploads
    # Grab the tools we need for WordPress' local-env.
    curl -sL https://github.com/WordPress/wordpress-develop/archive/master.zip -o /tmp/wordpress-develop.zip
    unzip -q /tmp/wordpress-develop.zip -d /tmp
    mv \
      /tmp/wordpress-develop-master/tools \
      /tmp/wordpress-develop-master/tests \
      /tmp/wordpress-develop-master/.env \
      /tmp/wordpress-develop-master/docker-compose.yml \
      /tmp/wordpress-develop-master/wp-cli.yml \
      /tmp/wordpress-develop-master/*config-sample.php \
      /tmp/wordpress-develop-master/package.json wordpress

    # Install WordPress.
    cd wordpress
    npm install dotenv wait-on
    npm run env:start
    sleep 10
    npm run env:install
    cd ..
    # Connect Gutenberg to WordPress.
    npm run env connect
    npm run env cli plugin activate wp-bootstrap-blocks

script:
  - composer lint
  - npm run lint
  - npm run test:e2e

deploy:
  provider: script
  script: scripts/deploy-wp-plugin.sh
  on:
    php: 7.2
    tags: true
    all_branches: true
