name: Lint Test Deploy

on: [push]

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
          composer install

      - name: Run linter
        run: npm run lint

      - name: Run PHP linter
        run: |
          npm run wp-env start
          npm run lint:php

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        wp: [ '5.7', '5.8' ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
          composer install

      - name: "Configure environment with WP ${{ matrix.wp }}"
        run: |
          echo -e '{\n\t"core": "WordPress/WordPress#${{ matrix.wp }}"\n}' > ./.wp-env.override.json

      - name: Install WordPress
        run: |
          chmod -R 767 ./ # TODO: Possibly integrate in wp-env
          npm run wp-env start

      - name: Running JavaScript E2E tests
        run: npm run test:e2e'

      - name: Running PHP unit tests
        run: npm run test:unit:php:ci

  tests-wp-59:
    name: Tests WordPress 5.9

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
          composer install

      - name: "Configure environment with WP 5.9"
        run: |
          echo -e '{\n\t"core": "https://wordpress.org/wordpress-5.9-beta2.zip"\n}' > ./.wp-env.override.json

      - name: Install WordPress
        run: |
          chmod -R 767 ./ # TODO: Possibly integrate in wp-env
          npm run wp-env start

      - name: Running JavaScript E2E tests
        run: npm run test:e2e'

      - name: Running PHP unit tests
        run: npm run test:unit:php:ci

  deploy-dry-run:
    name: '[DRY RUN] Deploy'

    # only run on master but not tags
    if: ${{ github.ref == 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/') }}

    needs: [ lint, tests, 'tests-wp-59' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - shell: bash
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          DRYRUN=true scripts/deploy-wp-plugin.sh

  deploy:
    name: Deploy

    # only run on tags
    if: startsWith(github.ref, 'refs/tags/')

    needs: [ lint, tests, 'tests-wp-59' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - shell: bash
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          scripts/deploy-wp-plugin.sh
