name: Unit Tests

on: [push]

jobs:
  unit-php:
    name: PHP

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Install WordPress
        run: |
          chmod -R 767 ./ # TODO: Possibly integrate in wp-env
          npm run wp-env start

      - name: Running the tests
        run: npm run test:unit:php:ci
